version: '2'
services:
    bankapp-app:
        image: bankapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bankapp-mysql:3306/bankapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bankapp-mysql:
        extends:
            file: mysql.yml
            service: bankapp-mysql
